services:
  postgres:
    image: postgres:latest
    container_name: dbyml

    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: dbnext

    ports:
      - "5464:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    restart: unless-stopped

volumes:
  postgres_data: